import { dateAfterDays } from '@/lib/dates';
import { AppState, DiagnosticQuestion, ModelAnswer, PracticeCard, ReviewCard, Section, UserProfile } from '@/lib/types';

export const sectionLabels: Record<Section, string> = {
  reading: 'Reading',
  listening: 'Listening',
  speaking: 'Speaking',
  writing: 'Writing',
};

export const defaultProfile: UserProfile = {
  name: 'Learner',
  targetScore: 120,
  testDate: dateAfterDays(3),
  dailyMinutes: 60,
  confidence: {
    reading: 0,
    listening: 0,
    speaking: 0,
    writing: 0,
  },
};

function speakingModel(response: string, structure: string[]): ModelAnswer {
  return {
    scoreBand: 'High 4/5 speaking signal',
    response,
    strengths: ['Answers the prompt immediately', 'Uses one clear support path', 'Keeps wording compact', 'Finishes with a complete thought'],
    structure,
  };
}

function writingModel(response: string, structure: string[]): ModelAnswer {
  return {
    scoreBand: 'High 4/5 writing signal',
    response,
    strengths: ['Clear task control', 'Specific support', 'Logical organization', 'Clean final connection'],
    structure,
  };
}

export const diagnosticQuestions: DiagnosticQuestion[] = [
  {
    id: 'r1',
    section: 'reading',
    subskill: 'vocabulary in context',
    prompt: 'A passage says that early observers considered the coastline “rugged,” with cliffs, narrow inlets, and uneven rock layers. The word rugged is closest in meaning to:',
    options: ['Smooth', 'Irregular', 'Temporary', 'Distant'],
    answer: 1,
    explanation: 'The surrounding details describe rough, uneven land, so irregular is the best contextual match.',
  },
  {
    id: 'r2',
    section: 'reading',
    subskill: 'factual detail',
    prompt: 'According to a short passage about seed dispersal, which factor helped the plant spread to nearby islands?',
    options: ['Its roots tolerated salt immediately', 'Its seeds floated for long periods', 'Its flowers opened only at night', 'Its leaves attracted grazing animals'],
    answer: 1,
    explanation: 'The passage directly states that the seeds could remain afloat long enough to reach nearby islands.',
  },
  {
    id: 'r3',
    section: 'reading',
    subskill: 'inference',
    prompt: 'A passage says a species began nesting earlier after spring temperatures rose over several decades. What is the safest inference?',
    options: ['The species now prefers colder habitats', 'Climate conditions likely affected nesting timing', 'The species stopped migrating entirely', 'Researchers misread all older data'],
    answer: 1,
    explanation: 'A repeated shift tied to warming supports a careful inference about climate influence, not extreme conclusions.',
  },
  {
    id: 'r4',
    section: 'reading',
    subskill: 'rhetorical purpose',
    prompt: 'Why does an author describe one unsuccessful restoration project before presenting a later successful one?',
    options: ['To show the later strategy solved a specific earlier problem', 'To argue that all restoration should end', 'To change the topic entirely', 'To focus only on personalities'],
    answer: 0,
    explanation: 'The failed case sets up contrast and shows why the improved method mattered.',
  },
  {
    id: 'r5',
    section: 'reading',
    subskill: 'pacing',
    prompt: 'If you are falling behind on a TOEFL reading passage, which adjustment is usually safest first?',
    options: ['Read every sentence twice', 'Skip the passage and guess all answers', 'Track paragraph purpose and hunt only for needed detail', 'Memorize unfamiliar vocabulary before continuing'],
    answer: 2,
    explanation: 'Fast passage mapping preserves structure and helps you return efficiently for specific evidence.',
  },
  {
    id: 'l1',
    section: 'listening',
    subskill: 'gist',
    prompt: 'In a campus conversation, a student explains that a chemistry lab overlaps with a required orientation. What is the main purpose of the conversation?',
    options: ['To complain about the professor', 'To solve a scheduling conflict', 'To join a new major', 'To request a dorm change'],
    answer: 1,
    explanation: 'The main issue is conflict resolution, so the conversation is about finding a workable schedule.',
  },
  {
    id: 'l2',
    section: 'listening',
    subskill: 'detail',
    prompt: 'A professor says one desert plant survives because a waxy surface slows water loss. Which detail is specifically stated?',
    options: ['The plant grows only in shade', 'The plant stores sugar in its roots', 'The waxy surface reduces evaporation', 'The leaves open only in winter'],
    answer: 2,
    explanation: 'That exact functional detail is given in the lecture.',
  },
  {
    id: 'l3',
    section: 'listening',
    subskill: 'inference',
    prompt: 'A student says, “I thought the paper was due next week, so I signed up for extra shifts.” What can be inferred?',
    options: ['The student already finished the assignment', 'The student misunderstood the deadline', 'The instructor changed majors', 'The student wants to drop the course immediately'],
    answer: 1,
    explanation: 'The student’s comment shows a mistaken assumption about timing.',
  },
  {
    id: 'l4',
    section: 'listening',
    subskill: 'organization',
    prompt: 'A lecture first defines a theory, then gives two case studies, then compares their outcomes. What should you track most carefully?',
    options: ['Only rare vocabulary', 'The structural shifts and transitions', 'Every joke the professor makes', 'Only the final sentence'],
    answer: 1,
    explanation: 'Listening questions often depend on following the lecture’s structure, not transcribing every word.',
  },
  {
    id: 'l5',
    section: 'listening',
    subskill: 'note-taking quality',
    prompt: 'What note-taking habit is strongest for TOEFL listening?',
    options: ['Write full sentences for everything', 'Capture main idea, examples, and contrast words', 'Ignore examples because they waste time', 'Copy the first minute exactly'],
    answer: 1,
    explanation: 'Compact structure-based notes support both gist and detail questions.',
  },
  {
    id: 's1',
    section: 'speaking',
    subskill: 'fluency',
    prompt: 'For an independent speaking task, which approach most improves fluency?',
    options: ['Use one clear reason and one specific example', 'List every idea you can think of', 'Pause often to restart the same sentence', 'Memorize a 25-second introduction'],
    answer: 0,
    explanation: 'A compact plan reduces hesitation and makes delivery smoother.',
  },
  {
    id: 's2',
    section: 'speaking',
    subskill: 'timing control',
    prompt: 'If you regularly run out of time in 45-second answers, what should you change first?',
    options: ['Add more background detail', 'Cut setup and keep one stronger support point', 'Speak much slower from start to finish', 'Memorize a longer template'],
    answer: 1,
    explanation: 'Overlong setup is a common timing problem. A single strong reason usually scores better than two rushed ones.',
  },
  {
    id: 's3',
    section: 'speaking',
    subskill: 'organization',
    prompt: 'What is the best basic structure for an integrated speaking summary?',
    options: ['Opinion first, sources later', 'Reading point, lecture response, then next pair', 'A long introduction about the topic', 'Disconnected details in the order you remember them'],
    answer: 1,
    explanation: 'TOEFL integrated speaking rewards clean source alignment.',
  },
  {
    id: 's4',
    section: 'speaking',
    subskill: 'clarity/pronunciation',
    prompt: 'Which habit helps clarity most when you are nervous?',
    options: ['Rush to fit more ideas in', 'Stress key content words and finish sentences cleanly', 'Whisper difficult words', 'Avoid transitions'],
    answer: 1,
    explanation: 'Clear emphasis and completed thoughts help listeners follow you even if your accent is strong.',
  },
  {
    id: 's5',
    section: 'speaking',
    subskill: 'response structure',
    prompt: 'Why is a simple repeatable template useful for speaking?',
    options: ['It replaces the need to understand the task', 'It keeps the response organized under time pressure', 'It guarantees a perfect score automatically', 'It lets you avoid giving examples'],
    answer: 1,
    explanation: 'Structure supports timing and coherence, but it still needs real content.',
  },
  {
    id: 'w1',
    section: 'writing',
    subskill: 'structure',
    prompt: 'Which choice usually makes an integrated writing response stronger?',
    options: ['Only summarize the reading', 'Match each lecture challenge to the exact reading claim it disputes', 'Write one extremely long paragraph', 'Add personal opinion throughout'],
    answer: 1,
    explanation: 'Good integrated writing depends on accurate source-to-source comparison.',
  },
  {
    id: 'w2',
    section: 'writing',
    subskill: 'coherence',
    prompt: 'Which revision most improves coherence?',
    options: ['Add clear transition logic between related points', 'Use difficult vocabulary in every sentence', 'Remove topic sentences', 'Repeat the thesis in all body sentences'],
    answer: 0,
    explanation: 'Readers score reasoning more easily when progression is explicit.',
  },
  {
    id: 'w3',
    section: 'writing',
    subskill: 'grammar control',
    prompt: 'Which pattern is most likely to lower a writing score if repeated often?',
    options: ['Minor variety in sentence length', 'Frequent errors in verb tense and agreement', 'One short concluding sentence', 'A direct topic sentence'],
    answer: 1,
    explanation: 'Persistent grammar breakdowns can interfere with meaning and reduce score reliability.',
  },
  {
    id: 'w4',
    section: 'writing',
    subskill: 'support quality',
    prompt: 'What usually makes a discussion response more convincing?',
    options: ['A clear stance plus one developed reason with a concrete example', 'Three vague reasons with no example', 'A long introduction with no position', 'Repeating another student’s words'],
    answer: 0,
    explanation: 'Specific support is more valuable than extra undeveloped claims.',
  },
  {
    id: 'w5',
    section: 'writing',
    subskill: 'integrated synthesis',
    prompt: 'In an integrated task, what should you avoid?',
    options: ['Showing how the lecture responds to the reading', 'Inventing outside examples and opinions that are not in the sources', 'Using source-based comparison words', 'Paraphrasing carefully'],
    answer: 1,
    explanation: 'Integrated writing is about source reporting, not adding your own ideas.',
  },
  {
    id: 'w6',
    section: 'writing',
    subskill: 'discussion response quality',
    prompt: 'For the Academic Discussion task, which strategy is usually best?',
    options: ['Respond directly to the prompt and contribute one fresh supporting point', 'Summarize the entire forum without a position', 'Write only two very short sentences', 'Ignore the other viewpoints completely'],
    answer: 0,
    explanation: 'The task rewards a direct contribution, not a generic summary.',
  },
];

export const practiceCards: Record<Section, PracticeCard[]> = {
  reading: [
    {
      id: 'pr-r-1',
      section: 'reading',
      title: 'Vocabulary in context: volcanic glass',
      subskill: 'vocabulary in context',
      prompt: 'A passage says obsidian was valued because it could be fractured into “precise” cutting edges. The word precise is closest in meaning to:',
      choices: ['Decorative', 'Accurate', 'Fragile', 'Ancient'],
      answer: 1,
      explanation: 'The passage focuses on exact cutting edges, so accurate is the best meaning in context.',
      xp: 18,
      followUp: 'What context clue around the word helped you eliminate two options quickly?',
    },
    {
      id: 'pr-r-2',
      section: 'reading',
      title: 'Factual detail: wetland restoration',
      subskill: 'factual detail',
      prompt: 'According to a short passage, why did birds return after the wetland was restored?',
      choices: ['A nearby highway was removed', 'New feeding and nesting habitat became available', 'Winter temperatures increased sharply', 'The wetland was converted into farmland'],
      answer: 1,
      explanation: 'The return of habitat directly explains the birds’ return.',
      xp: 18,
      followUp: 'Which exact noun phrase in the prompt signals this is a detail question rather than an inference question?',
    },
    {
      id: 'pr-r-3',
      section: 'reading',
      title: 'Inference: ancient trade routes',
      subskill: 'inference',
      prompt: 'A passage notes that similar pottery styles appeared in distant towns that had regular river contact. What is the safest inference?',
      choices: ['The towns were politically united', 'River travel likely helped cultural exchange', 'All pottery was made in one village', 'The pottery styles were accidental'],
      answer: 1,
      explanation: 'Shared styles plus regular river contact support a cautious inference about exchange.',
      xp: 20,
      followUp: 'Why would “politically united” be too strong even if trade probably occurred?',
    },
    {
      id: 'pr-r-4',
      section: 'reading',
      title: 'Rhetorical purpose: failed prototype',
      subskill: 'rhetorical purpose',
      prompt: 'An author describes a failed bridge design before explaining a later redesign. Why include the failed design?',
      choices: ['To show the redesign addressed a known weakness', 'To prove engineers should stop building bridges', 'To provide comic relief', 'To hide the main conclusion'],
      answer: 0,
      explanation: 'The earlier failure explains why the redesign matters and what problem it solved.',
      xp: 20,
      followUp: 'State the purpose in one short clause beginning with “to show...”.',
    },
    {
      id: 'pr-r-5',
      section: 'reading',
      title: 'Reference: pronoun target',
      subskill: 'reference',
      prompt: 'A passage says, “The glaciers retreated quickly after the climate warmed, and this exposed new valleys for plant growth.” What does this refer to?',
      choices: ['The climate', 'The plant growth', 'The glaciers’ retreat', 'The valleys'],
      answer: 2,
      explanation: 'This points back to the immediately preceding event: the retreat of the glaciers.',
      xp: 16,
      followUp: 'When TOEFL asks reference questions, what is your first search move?',
    },
    {
      id: 'pr-r-6',
      section: 'reading',
      title: 'Negative factual information: textile dyes',
      subskill: 'negative factual information',
      prompt: 'The passage mentions that early textile dyes came from plants, minerals, and shellfish. Which answer is NOT mentioned as a source?',
      choices: ['Plants', 'Minerals', 'Shellfish', 'Synthetic polymers'],
      answer: 3,
      explanation: 'The first three are explicitly listed, so the unmentioned option is synthetic polymers.',
      xp: 18,
      followUp: 'How can you avoid accidentally choosing a true detail on NOT/EXCEPT questions?',
    },
    {
      id: 'pr-r-7',
      section: 'reading',
      title: 'Sentence summary: forest layers',
      subskill: 'summary',
      prompt: 'A paragraph explains that rainforests have layered vegetation, and each layer supports different animal behavior because light, humidity, and food access vary. Which summary is best?',
      choices: ['Rainforests are difficult to explore because they are dark.', 'Different forest layers create distinct living conditions that shape animal activity.', 'Animals in rainforests all prefer the top layer.', 'Humidity matters more than food in every ecosystem.'],
      answer: 1,
      explanation: 'The best summary captures the full causal relationship without narrowing it too much.',
      xp: 22,
      followUp: 'What idea did choices A and C leave out that made them too narrow?',
    },
    {
      id: 'pr-r-8',
      section: 'reading',
      title: 'Pacing reset: long passage control',
      subskill: 'pacing',
      prompt: 'You spend too long on one difficult paragraph in a reading set. What is the highest-yield recovery move?',
      choices: ['Restart the passage from the beginning', 'Mark the paragraph purpose, move on, and return only if a question requires it', 'Translate each sentence word by word', 'Guess every remaining answer immediately'],
      answer: 1,
      explanation: 'TOEFL rewards strategic coverage. Capture function first, then return for needed evidence.',
      xp: 16,
      followUp: 'Write a 5-word label you could give a tough paragraph instead of rereading everything.',
    },
    {
      id: 'pr-r-9',
      section: 'reading',
      title: 'Sentence insertion: pronoun placement',
      subskill: 'sentence insertion',
      prompt: 'Sentence to insert: “These changes made the new habitat easier for young birds to use.” Paragraph: Restoration workers first removed invasive reeds from the marsh. [A] They then opened narrow channels so water could circulate again. [B] Young fish returned within a season. [C] The larger bird population recovered more slowly. [D] Where does the sentence fit best?',
      choices: ['A', 'B', 'C', 'D'],
      answer: 2,
      explanation: '“These changes” must refer to the removal and water-channel work, and the sentence prepares for the young fish/bird recovery evidence.',
      xp: 22,
      followUp: 'Name the noun or action that the pronoun points back to before choosing the slot.',
    },
  ],
  listening: [
    {
      id: 'pr-l-1',
      section: 'listening',
      title: 'Conversation gist: missed rehearsal',
      subskill: 'gist',
      prompt: 'Conversation note: A student missed orchestra rehearsal because of a bus delay. The director suggests arriving early and reviewing a recording. What is the main outcome?',
      choices: ['The student quits the orchestra', 'A practical recovery plan is offered', 'The director cancels the performance', 'The student changes majors'],
      answer: 1,
      explanation: 'The conversation ends with a workable solution, not a major conflict.',
      xp: 18,
      followUp: 'Which two details confirmed the outcome rather than just the problem?',
    },
    {
      id: 'pr-l-2',
      section: 'listening',
      title: 'Lecture detail: coral spawning',
      subskill: 'detail',
      prompt: 'A marine biology lecture explains that many corals release eggs and sperm at the same time after temperature and moonlight cues. Which detail is stated?',
      choices: ['Corals migrate seasonally', 'Reproduction is timed by environmental signals', 'Corals reproduce only in freshwater', 'Spawning happens randomly every month'],
      answer: 1,
      explanation: 'The lecture explicitly ties spawning timing to specific environmental cues.',
      xp: 18,
      followUp: 'What note abbreviation could capture “temperature and moonlight cues” quickly?',
    },
    {
      id: 'pr-l-3',
      section: 'listening',
      title: 'Speaker attitude: library renovation',
      subskill: 'speaker attitude',
      prompt: 'A student says, “I know the renovation will help eventually, but finding a quiet seat this month has been impossible.” What is the student’s attitude?',
      choices: ['Fully enthusiastic now', 'Cautiously positive but currently frustrated', 'Completely indifferent', 'Amused by the inconvenience'],
      answer: 1,
      explanation: 'The student accepts the long-term benefit but expresses clear present frustration.',
      xp: 20,
      followUp: 'Which phrase signaled contrast between the long-term and short-term attitude?',
    },
    {
      id: 'pr-l-4',
      section: 'listening',
      title: 'Organization map: migration lecture',
      subskill: 'organization',
      prompt: 'Mini lecture outline: the professor defines migration, gives one bird example, then contrasts it with insect migration. What structural note matters most?',
      choices: ['The definition followed by example and contrast', 'Every adjective used in the bird example', 'Only the insect names', 'The first sentence only'],
      answer: 0,
      explanation: 'The lecture’s organization will help with both gist and relationship questions.',
      xp: 20,
      followUp: 'Write the outline as three short bullets.',
    },
    {
      id: 'pr-l-5',
      section: 'listening',
      title: 'Inference: professor office hours',
      subskill: 'inference',
      prompt: 'A professor says, “Bring your outline tomorrow instead of the full draft, and we can prevent the same structural problem.” What can be inferred?',
      choices: ['The student already earned a high grade', 'The student had a structure issue before', 'The assignment was cancelled', 'The professor dislikes drafts'],
      answer: 1,
      explanation: 'The phrase “the same structural problem” implies that this issue has already appeared.',
      xp: 20,
      followUp: 'What exact wording made this an inference question rather than a direct detail question?',
    },
    {
      id: 'pr-l-6',
      section: 'listening',
      title: 'Function: why mention the field trip?',
      subskill: 'function',
      prompt: 'In a geology lecture, the professor mentions a field trip where students misidentified rock layers. Why does the professor mention this?',
      choices: ['To change the topic to transportation', 'To illustrate how similar rock layers can still be distinguished by context', 'To complain about student behavior', 'To announce next week’s homework only'],
      answer: 1,
      explanation: 'The anecdote functions as an example supporting the academic point.',
      xp: 22,
      followUp: 'Finish this sentence: “The anecdote is there to illustrate that...”',
    },
    {
      id: 'pr-l-7',
      section: 'listening',
      title: 'Note-taking quality: economics lecture',
      subskill: 'note-taking quality',
      prompt: 'A lecture compares two pricing strategies and gives one advantage and one risk for each. Which note style is strongest?',
      choices: ['Write both strategies in a T-chart with one pro and one risk each', 'Write full paragraphs for the opening minute', 'Ignore the risks and copy only the examples', 'Record only the professor’s jokes'],
      answer: 0,
      explanation: 'A simple comparative note structure makes later questions easier to answer.',
      xp: 16,
      followUp: 'Sketch the T-chart labels you would use.',
    },
    {
      id: 'pr-l-8',
      section: 'listening',
      title: 'Connecting content: cause and effect',
      subskill: 'cause and effect',
      prompt: 'A history lecture explains that a port city expanded after a canal reduced shipping time and cost. What relationship is emphasized?',
      choices: ['Cause and effect', 'Chronological contrast only', 'Definition and classification', 'Problem without solution'],
      answer: 0,
      explanation: 'The canal change causes lower transport costs, which supports city growth.',
      xp: 18,
      followUp: 'What two-note symbols could help you capture this relationship faster next time?',
    },
    {
      id: 'pr-l-9',
      section: 'listening',
      title: 'Campus roles: professor, adviser, registrar',
      subskill: 'campus roles',
      prompt: 'A student asks where to fix a wrong course registration record. Which office is most likely to help?',
      choices: ['Professor', 'Academic adviser', 'Registrar', 'Campus dining office'],
      answer: 2,
      explanation: 'A registrar handles official registration records and files. Professors help with class expectations or grades; advisers help choose plans and schedules.',
      xp: 18,
      followUp: 'Sort the problem first: assignment/class help, schedule planning, or official record?',
    },
  ],
  speaking: [
    {
      id: 'pr-s-1',
      section: 'speaking',
      title: 'Independent: study space preference',
      subskill: 'fluency',
      prompt: 'Some students study best in a silent library, while others prefer a café or shared space. Which do you prefer and why? Answer in about 45 seconds with one clear reason and one example.',
      explanation: 'Strong answers take a position immediately, support it with one specific example, and avoid adding a second weak reason.',
      modelAnswer: speakingModel(
        'I prefer studying in a silent library because it helps me stay focused on difficult work. For example, when I prepare for a biology exam, I need to read diagrams and remember details, and background conversation makes me lose my place. In the library, I can finish one topic faster and check my notes more carefully. So for serious studying, a quiet library is much better for me than a café.',
        ['Preference', 'Reason', 'Specific example', 'Final result'],
      ),
      xp: 24,
      followUp: 'After recording, identify one place where you hesitated and rewrite that sentence more simply.',
    },
    {
      id: 'pr-s-2',
      section: 'speaking',
      title: 'Independent: early class or late class',
      subskill: 'timing control',
      prompt: 'Would you rather take an important class early in the morning or late in the afternoon? Give one main reason and one concrete example in 45 seconds.',
      explanation: 'Use a 10-second opening, 25-second example, and 5-second finish so you do not rush the ending.',
      modelAnswer: speakingModel(
        'I would rather take an important class early in the morning because my concentration is strongest then. For instance, in a math class I need to follow each step carefully, and after a long day I make small mistakes more often. If the class is early, I can listen actively and review the material before other assignments begin. That makes the morning schedule more useful for a difficult subject.',
        ['Choice', 'Reason', 'Class example', 'Result'],
      ),
      xp: 24,
      followUp: 'Estimate how many seconds you spent before reaching your example. Could you cut that by five seconds?',
    },
    {
      id: 'pr-s-3',
      section: 'speaking',
      title: 'Integrated campus: bike-share proposal',
      subskill: 'organization',
      prompt: 'Reading: the university wants to expand the bike-share system to reduce traffic and parking pressure. Listening: a student supports the goal but argues the current station locations are too limited and helmets are hard to borrow. Summarize the proposal and the student’s response in 60 seconds.',
      explanation: 'Organize by source relationship: proposal point, student concern, then next proposal point, student concern.',
      modelAnswer: speakingModel(
        'The university proposes expanding the bike-share system to reduce traffic and parking pressure. The student agrees with the general goal, but he thinks the current plan has problems. First, the stations are too limited, so many students may not find a bike near their classes or dorms. Second, helmets are hard to borrow, which makes the system less practical and safe. Overall, he supports bike sharing but wants better locations and easier helmet access.',
        ['Proposal', 'Student position', 'Problem one', 'Problem two', 'Overall response'],
      ),
      xp: 26,
      followUp: 'Did you clearly separate the reading claims from the student’s objections?',
      responseMode: 'learner_answer',
      sourceMaterialCompleteness: 'summary_only',
      materials: {
        reading: 'The university wants to expand the bike-share system to reduce traffic and parking pressure.',
        listening: 'A student supports the goal but says current station locations are too limited and helmets are hard to borrow.',
        template: 'Proposal -> student response -> reason one -> reason two.',
      },
    },
    {
      id: 'pr-s-4',
      section: 'speaking',
      title: 'Integrated academic: bee communication',
      subskill: 'response structure',
      prompt: 'Lecture summary: the professor explains that bees communicate food location through movement patterns and then gives one example involving distance and another involving direction. Summarize the lecture in 60 seconds.',
      explanation: 'Use a short main idea sentence, then deliver the two examples in the same order the professor used.',
      modelAnswer: speakingModel(
        'The professor explains that bees communicate the location of food through movement patterns. One part of the movement can show distance, so other bees know whether the food source is nearby or farther away. Another part can show direction, which helps the bees travel toward the right area. These examples show that the movement is not random; it gives other bees practical information about where to find food.',
        ['Main idea', 'Distance example', 'Direction example', 'Final meaning'],
      ),
      xp: 26,
      followUp: 'Did your answer keep the lecture order, or did you jump between examples?',
      responseMode: 'learner_answer',
      sourceMaterialCompleteness: 'summary_only',
      materials: {
        lecture:
          'The professor explains that bees communicate food location through movement patterns, then gives one example involving distance and another involving direction.',
        template: 'Main idea -> distance example -> direction example -> final summary.',
      },
    },
    {
      id: 'pr-s-5',
      section: 'speaking',
      title: 'Delivery redo: clarity under stress',
      subskill: 'clarity/pronunciation',
      prompt: 'Re-answer any earlier speaking card, but this time slow slightly, stress key nouns and verbs, and make every final word audible. Record and self-rate the result.',
      explanation: 'Clarity improves when ideas are slightly fewer but sentence endings are complete and emphasized.',
      modelAnswer: speakingModel(
        'I prefer studying in a silent library because difficult work needs full attention. For example, when I study science, I have to connect definitions with diagrams, and noise makes me reread the same line. In a quiet room, I can finish the task faster and remember the details better. For that reason, the library is the best place for serious studying.',
        ['Direct answer', 'One reason', 'Controlled example', 'Audible final sentence'],
      ),
      xp: 22,
      followUp: 'Which word endings disappeared in your first attempt and were clearer in the redo?',
    },
    {
      id: 'pr-s-6',
      section: 'speaking',
      title: 'Campus conversation: advising conflict',
      subskill: 'source integration',
      prompt: 'Conversation summary: a student wants to add a class but cannot meet the advising deadline because of a regional sports trip. The advisor offers two options and explains why one is better. Summarize the problem and the recommended solution in 60 seconds.',
      explanation: 'Integrated speaking answers are stronger when you name the problem clearly, then explain the recommendation and reason without adding personal opinion.',
      modelAnswer: speakingModel(
        'The student wants to add a class, but he cannot meet the advising deadline because he will be away for a regional sports trip. The advisor gives him two options, but recommends the one that keeps his schedule official before he leaves. This is better because waiting until after the trip could make the class full or delay approval. So the student should handle the paperwork early and use the later option only if the first plan fails.',
        ['Problem', 'Options', 'Recommended solution', 'Reason'],
      ),
      xp: 24,
      followUp: 'Did you include both the problem and the reason the recommended solution is better?',
      responseMode: 'learner_answer',
      sourceMaterialCompleteness: 'summary_only',
      materials: {
        conversation:
          'A student wants to add a class but cannot meet the advising deadline because of a regional sports trip. The advisor offers two options and explains why one is better.',
        template: 'Problem -> option/recommendation -> reason -> result.',
      },
    },
    {
      id: 'pr-s-7',
      section: 'speaking',
      title: 'Template reveal: integrated speaking',
      subskill: 'integrated speaking template',
      prompt: 'Use this optional scaffold for a 60-second integrated answer: “The reading announces ___. The student/professor agrees/disagrees because ___. First, ___. Second, ___. Overall, the listening shows ___.” Record a response to any earlier integrated prompt using only these five beats.',
      explanation: 'The template is a temporary rail, not a script to memorize. It protects source order, reasons, and a clean final sentence.',
      modelAnswer: speakingModel(
        'The reading announces a plan to expand the bike-share system. The student partly agrees because reducing traffic is a good goal, but he thinks the plan is incomplete. First, the current station locations are too limited, so many students may not find bikes where they need them. Second, helmets are hard to borrow, which creates a safety problem. Overall, the listening shows that the proposal needs better access before it can work well.',
        ['Reading announcement', 'Listener response', 'First reason', 'Second reason', 'Overall result'],
      ),
      xp: 24,
      followUp: 'After recording, remove one unnecessary template phrase while keeping the same structure.',
      responseMode: 'template_only',
      sourceMaterialCompleteness: 'template_only',
      materials: {
        template:
          'The reading announces ___. The student/professor agrees/disagrees because ___. First, ___. Second, ___. Overall, the listening shows ___.',
      },
    },
  ],
  writing: [
    {
      id: 'pr-w-1',
      section: 'writing',
      title: 'Integrated writing: urban farming',
      subskill: 'integrated synthesis',
      prompt: 'Reading: Urban rooftop farms can improve city food supply because they use unused space, reduce shipping distance, and teach communities about food production. Lecture: The professor argues these benefits are overstated because rooftop yields are limited, setup costs are high, and educational value does not solve supply problems. Write 180-240 words comparing the lecture with the reading.',
      explanation: 'Pair each lecture objection directly with the reading claim it challenges. Do not add your own opinion.',
      modelAnswer: writingModel(
        'The lecture challenges the reading’s claim that rooftop farms can significantly improve city food supply. First, the reading says rooftop farms use unused space, but the professor argues that their yields are too limited to produce a meaningful amount of food for a city. This weakens the idea that available roof space automatically creates a strong food source. Second, the reading claims that rooftop farms reduce shipping distance. The professor responds that setup and maintenance costs are high, so the projects may not be efficient even if the food travels a shorter distance. Finally, the reading says rooftop farms teach communities about food production. The professor agrees that education may occur, but explains that this benefit does not solve the practical supply problem. Overall, the lecture shows that the reading’s benefits are real but overstated.',
        ['Intro source relationship', 'Claim one and challenge', 'Claim two and challenge', 'Claim three and challenge', 'Overall conclusion'],
      ),
      xp: 28,
      followUp: 'Check whether each body paragraph names the reading claim first and the lecture challenge second.',
      responseMode: 'learner_answer',
      sourceMaterialCompleteness: 'summary_only',
      materials: {
        reading:
          'Urban rooftop farms can improve city food supply because they use unused space, reduce shipping distance, and teach communities about food production.',
        lecture:
          'The professor argues these benefits are overstated because rooftop yields are limited, setup costs are high, and educational value does not solve supply problems.',
        template: 'Reading claim -> lecture challenge -> result.',
      },
    },
    {
      id: 'pr-w-2',
      section: 'writing',
      title: 'Integrated writing: ancient monument theory',
      subskill: 'structure',
      prompt: 'Reading: A monument may have been built for defense because it sits on high ground, has thick walls, and overlooks trade routes. Lecture: The professor argues the site was ceremonial, noting poor storage space, decorative wall carvings, and limited military visibility in bad weather. Write 180-240 words explaining how the lecture challenges the reading.',
      explanation: 'A strong structure usually means one paragraph per reading claim and a matching lecture rebuttal in each paragraph.',
      modelAnswer: writingModel(
        'The lecture challenges the reading’s theory that the monument was built for defense. The reading first argues that the site’s high location made it useful for protection. However, the professor explains that the area had poor storage space, which would make it difficult for soldiers to remain there during a real conflict. The reading also points to the thick walls as evidence of a defensive purpose. The professor responds that the wall carvings are decorative, suggesting a ceremonial function rather than a military one. Finally, the reading says the monument overlooks trade routes. The professor weakens this point by noting that visibility was limited in bad weather, so the location would not always help defenders watch movement. Therefore, the lecture presents several reasons why a ceremonial explanation is stronger than the defense theory.',
        ['Intro source relationship', 'Location challenge', 'Wall-purpose challenge', 'Visibility challenge', 'Conclusion'],
      ),
      xp: 28,
      followUp: 'Did any paragraph drift into summary of only one source instead of comparison?',
      responseMode: 'learner_answer',
      sourceMaterialCompleteness: 'summary_only',
      materials: {
        reading:
          'A monument may have been built for defense because it sits on high ground, has thick walls, and overlooks trade routes.',
        lecture:
          'The professor argues the site was ceremonial, noting poor storage space, decorative wall carvings, and limited military visibility in bad weather.',
        template: 'Reading reason -> lecture challenge -> why the challenge matters.',
      },
    },
    {
      id: 'pr-w-3',
      section: 'writing',
      title: 'Academic Discussion: mandatory service',
      subskill: 'discussion response quality',
      prompt: 'Professor: Some universities require students to complete community service before graduation. Is this a good idea? Student A says yes because it builds civic responsibility. Student B says no because students already face heavy workloads. Write 120-180 words contributing your opinion with one fresh reason and one specific example.',
      explanation: 'Respond directly to the discussion and contribute something new instead of repeating one classmate’s argument.',
      modelAnswer: writingModel(
        'I think community service should be required, but the requirement should be small and flexible. My main reason is that service can help students connect classroom knowledge to real problems. For example, an engineering student who volunteers with a local housing group may see how design decisions affect accessibility for older residents. That kind of experience can make academic work feel more responsible and practical. However, universities should let students choose approved projects that fit their schedules, because a heavy requirement could create the workload problem Student B mentions. A limited service requirement would give students useful community experience without turning it into another stressful class.',
        ['Position', 'Fresh reason', 'Specific example', 'Balanced concession', 'Final judgment'],
      ),
      xp: 22,
      followUp: 'Underline the single sentence that most clearly adds your own contribution to the thread.',
    },
    {
      id: 'pr-w-4',
      section: 'writing',
      title: 'Academic Discussion: recorded lectures',
      subskill: 'support quality',
      prompt: 'Professor: Should universities record every lecture and post it online? Student A says yes because it helps review. Student B says no because attendance may drop. Write 120-180 words giving your own opinion and support it with one developed example.',
      explanation: 'One developed reason with a concrete example is usually better than several shallow reasons.',
      modelAnswer: writingModel(
        'Universities should record lectures and post them online because recordings make review more accurate. Students often miss small details while taking notes, especially in courses with formulas, diagrams, or unfamiliar vocabulary. For example, in a chemistry lecture, a student may understand the main concept in class but later forget one step in the professor’s explanation. A recording lets the student replay that exact section and correct the notes before an exam. I understand the concern that attendance may drop, but professors can still require participation or in-class activities. The academic benefit of accurate review is more important than the risk that some students will use recordings lazily.',
        ['Position', 'Reason', 'Course example', 'Concession', 'Final judgment'],
      ),
      xp: 22,
      followUp: 'Could your example be made more concrete by adding a class, event, or consequence?',
    },
    {
      id: 'pr-w-5',
      section: 'writing',
      title: 'Revision drill: coherence and transitions',
      subskill: 'coherence',
      prompt: 'Choose any earlier writing response. Rewrite it with clearer topic sentences, stronger transitions, and cleaner paragraph focus. Save both the original draft and the revision.',
      explanation: 'Local scoring is modest, so the best value comes from explicit revision that makes logic easier to follow.',
      modelAnswer: writingModel(
        'Original idea: Online lectures are useful because students can review them. Revised response: Universities should post lecture recordings because they help students repair gaps in their notes. For example, if a student misses one step in a biology explanation, the recording allows the student to replay that section and correct the mistake before studying for an exam. This support is especially valuable for international students who may understand the main idea in class but need a second listen for technical vocabulary. Therefore, recordings should not replace attendance, but they should be available as a review tool.',
        ['Original focus', 'Clear revised claim', 'Specific example', 'Transition to audience benefit', 'Controlled conclusion'],
      ),
      xp: 20,
      followUp: 'Name one transition you added that clarified the relationship between two ideas.',
    },
    {
      id: 'pr-w-6',
      section: 'writing',
      title: 'Editing drill: grammar control',
      subskill: 'grammar control',
      prompt: 'Write a 140-180 word response to this prompt: “Is it better for students to specialize early or explore many subjects first?” Then spend a revision pass checking verb tense, articles, sentence boundaries, and subject-verb agreement.',
      explanation: 'This card rewards a visible editing pass because repeated grammar errors can quietly cap an otherwise strong response.',
      modelAnswer: writingModel(
        'I believe students should explore many subjects before they specialize because early exploration helps them make better long-term choices. Many students choose a major before they understand what daily work in that field feels like. For example, a student who thinks she wants business may take psychology, statistics, and writing classes and discover that market research fits her interests better than general management. This broader experience can prevent costly changes later. Specializing early can be useful for students with a clear professional goal, but most students benefit from testing several fields first. After that, they can specialize with stronger confidence and a clearer reason.',
        ['Position', 'Reason', 'Specific student example', 'Concession', 'Conclusion'],
      ),
      xp: 20,
      followUp: 'List the two grammar patterns you corrected most often in your revision.',
    },
    {
      id: 'pr-w-7',
      section: 'writing',
      title: 'Outline builder: integrated writing',
      subskill: 'integrated writing outline',
      prompt: 'Before drafting, fill this outline: Reading claim 1 -> Lecture challenge 1; Reading claim 2 -> Lecture challenge 2; Reading claim 3 -> Lecture challenge 3. Then write one body paragraph from one pair using present tense and no personal opinion.',
      explanation: 'Integrated writing becomes easier when every body paragraph has a clear source pair: what the reading claims and how the lecture challenges it.',
      modelAnswer: writingModel(
        'Reading claim 1 -> rooftop farms use unused space. Lecture challenge 1 -> yields are too limited to affect the city food supply. Reading claim 2 -> rooftop farms reduce shipping distance. Lecture challenge 2 -> setup and maintenance costs are high. Reading claim 3 -> rooftop farms educate communities. Lecture challenge 3 -> education does not solve supply problems. Body paragraph model: First, the reading claims that rooftop farms make productive use of empty roof space. The lecture challenges this point by explaining that the amount of food produced is usually limited, so the farms cannot supply a large city in a meaningful way.',
        ['Three source pairs', 'Body paragraph topic', 'Reading claim', 'Lecture challenge', 'Result'],
      ),
      xp: 26,
      followUp: 'Check whether your paragraph has both source sides, not just a reading summary or lecture summary.',
      responseMode: 'template_only',
      sourceMaterialCompleteness: 'template_only',
      materials: {
        template: 'Reading claim 1 -> Lecture challenge 1; Reading claim 2 -> Lecture challenge 2; Reading claim 3 -> Lecture challenge 3.',
      },
    },
  ],
};

export const starterReviewQueue: ReviewCard[] = [
  {
    id: 'rev-1',
    section: 'reading',
    subskill: 'inference',
    prompt: 'Inference check: what evidence rule should you apply before choosing an answer?',
    answer: 'Choose only the idea that is strongly supported by the passage, not by outside knowledge or a stronger claim than the text allows.',
    dueDate: new Date().toISOString(),
    interval: 1,
  },
  {
    id: 'rev-2',
    section: 'listening',
    subskill: 'organization',
    prompt: 'Listening notes: what should you prioritize first in a lecture?',
    answer: 'Track the main idea and the structure shifts such as definition, example, contrast, cause, or solution.',
    dueDate: new Date().toISOString(),
    interval: 1,
  },
  {
    id: 'rev-3',
    section: 'speaking',
    subskill: 'timing control',
    prompt: 'Speaking timing rule: what is the safest first fix if you keep running long?',
    answer: 'Reduce setup and keep one stronger supporting point so the answer finishes cleanly.',
    dueDate: new Date().toISOString(),
    interval: 1,
  },
  {
    id: 'rev-4',
    section: 'writing',
    subskill: 'integrated synthesis',
    prompt: 'Integrated writing rule: what must each body paragraph usually do?',
    answer: 'Identify a reading claim and explain how the lecture challenges or weakens that exact point.',
    dueDate: new Date().toISOString(),
    interval: 1,
  },
];

export const initialState: AppState = {
  onboarded: false,
  profile: defaultProfile,
  diagnosticFormId: 'baseline',
  diagnosticCompleted: false,
  diagnosticAnswers: {},
  sectionScores: {
    reading: 0,
    listening: 0,
    speaking: 0,
    writing: 0,
  },
  subskillScores: {},
  track: 'Foundation',
  xp: 0,
  streak: 0,
  lastActiveDate: '',
  reviewQueue: [],
  errorLog: [],
  practiceHistory: [],
  writingDrafts: [],
  speakingAttempts: [],
  miniMockAttempts: [],
};
